@startuml name diagramaTp

title Diagrama de clases TP

abstract class Vehiculo{
    - numMatricula: number
    - estado: EstadoVehiculo
    - datosMantenimiento: DatosMantenimiento
    - datosEstadistica: DatosEstadistica
    - kilometros: number
    - logicaTarifa: Tarifa

    --Getters_Y_Setters--
}

class Sedan extends Vehiculo{}
class Suv extends Vehiculo{}
class Compacto extends Vehiculo{}

class EstrategiaSegunTemporada{
    +setEstrategiaTemporada(fecha: Date)
}

interface EstrategiaTemporada{
    tarifaBaseTemporada(tarifaBase: number)
}

class EstrategiaTemporadaAlta implements EstrategiaTemporada{}

class EstrategiaTemporadaBaja implements EstrategiaTemporada{}

class EstrategiaTemporadaMedia implements EstrategiaTemporada{}

class DatosEstadistica{
    -cantidadDeVecesAlquilado: number
    -ingresosAlquiler: number
    -costosMantenimiento: number

    --Getters_Y_Setters--
    +calcularRentabilidad(): number
}

class Mantenimiento{
    - vehiculo: Vehiculo
    - fechaInicio: Date
    - DURACION_MS : number

    +horasTranscurridas(fechaActual: Date): number
    +informeHorasTranscurridas(fechaActual: Date): boolean
    +finalizar(fechaActual: Date): void
}

class DatosMantenimiento{
    -kmUltimoMantenimiento: number
    -fechaUltimoMantenimiento: Date 
    -alquileresCantidad: number

    --Getters_Y_Setters--
    + calculadoraFecha(): number
}

interface Tarifa{
    calcularKm: CalcularKilometros
    calcularTemporada: CalcularTemporada
    +calcularTarifa(reserva: Reserva): number
}

class tarifaSuv implements Tarifa{}

class tarifaCompacto implements Tarifa{}

class tarifaSedan implements Tarifa{}

class Reserva{
    -idReserva: number
    -fechaInicio: Fecha
    -fechaFinalizacion: Fecha
    -vehiculo: Vehiculo
    -kmIniciales: number
    -kmFinales: number

    --Getters_Y_Setters--
    +calcularCantidadDias(): number
    +calcularPrecioReserva(): number
}

class CalcularKilometros{
    +promedioKmDiarios(dias: number): number
    +calcularKmTotales(kmIniciales: number, kmFinales: number): number
}

enum EstadoVehiculo{
    EN_MANTENIMIENTO,
    DISPONIBLE,
    EN_ALQUILER,
    NECESITA_LIMPIEZA,
}

class Facturacion {
    - _EXTRA_MANTENIMIENTO: number
    - disponibilidad: Disponibilidad

    - calcularMontoBase(reserva: Reserva): number
    - calcularExtraPorMantenimiento(reserva: Reserva): number
    + calcularMontoFinal(reserva: Reserva): number
}

class Administracion{
    -vehiculos: Map<matricula: number, vehiculo>
    -reservas: Map<idReserva: number,Reserva>
    -verificadorDisponibilidad: Disponibilidad
    -controladorDeEstadisticas: Estadistica

    --Getters_Y_Setters--
    +obtenerVehiculoDeReserva(r: Reserva): Vehiculo
    +actualizarMantenimiento(vehiculo: Vehiculo, fechaActual: Date): void
    +procesarReserva(reserva: Reserva): boolean
    +entregarVehiculo(reserva: Reserva): void
    +recibirVehiculo(reserva: Reserva): void
}

class Disponibilidad{
    + estaDisponible(reserva: Reserva, Reserva[]): boolean
    + necesitaMantenimiento(r: Reserva): boolean
}

class Estadistica{
    + vehiculoMasAlquilado(vehiculos: Map<Vehiculo>): Vehiculo
    + menosRentabilidad(vehiculos: Map<Vehiculo>): Vehiculo
    + mayorRentabilidad(vehiculos: Map<Vehiculo>): Vehiculo
    + porcentajeEnAlquiler(vehiculos: Map<Vehiculo>): number
    + generarReporte(vehiculos: Map<Vehiculo>): void
}


' Relaciones
Vehiculo *-- Tarifa
Administracion *-- Vehiculo
Disponibilidad *-- Reserva
Reserva *-r- CalcularKilometros
Administracion *-- Disponibilidad
Administracion <-- Reserva
Vehiculo *-u- DatosEstadistica
Vehiculo *-l- DatosMantenimiento
Vehiculo *-r- Estadistica
EstrategiaSegunTemporada <-- Tarifa
EstrategiaTemporada <-l- Tarifa
Vehiculo *-d- Mantenimiento
Administracion <-- Estadistica
Facturacion <-- Disponibilidad

@enduml